version: '3.8'

services:
  db:
    image: quay.io/sclorg/postgresql-12-c8s
    container_name: db
    hostname: db
    environment:
      POSTGRESQL_PASSWORD: velryba
      POSTGRESQL_USER: openscanhub
      POSTGRESQL_DATABASE: openscanhub
    ports:
      - "5432:5432"
    networks:
      - internal-network

  osh-hub:
    image: osh-hub
    build:
      context: .
      dockerfile: ./containers/hub/Dockerfile
    container_name: osh-hub
    hostname: osh-hub
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - internal-network
    volumes:
      - ./:/src:z
    stdin_open: true
    tty: true

  osh-worker:
    image: osh-worker
    build:
      context: .
      dockerfile: ./containers/worker.Dockerfile
    container_name: osh-worker
    hostname: osh-worker
    depends_on:
      - osh-hub
    networks:
      - internal-network
    volumes:
      - ./:/src:z
    privileged: true
    stdin_open: true
    tty: true

  osh-client:
    image: osh-client
    build:
      context: .
      dockerfile: ./containers/client.Dockerfile
    container_name: osh-client
    hostname: osh-client
    depends_on:
      - osh-hub
    networks:
      - internal-network
    volumes:
      - ./:/src:z
    stdin_open: true
    tty: true
    profiles:
      - full-dev

networks:
  internal-network:
