version: '3.8'

services:
  db:
    image: docker.io/postgres:12
    container_name: db
    hostname: db
    environment:
      POSTGRES_PASSWORD: velryba
      POSTGRES_USER: openscanhub
      POSTGRES_DB: openscanhub
    ports:
      - "5432:5432"
    networks:
      - internal-network

  fedora-osh-hub:
    image: fedora-osh-hub
    volumes:
      - ./:/src:ro,z
    build:
      context: .
      dockerfile: ./fedora-infra/Dockerfile
    container_name: fedora-osh-hub
    hostname: fedora-osh-hub
    depends_on:
      - db
    ports:
      - "8000:80"
      - "8443:443"
    networks:
      - internal-network
    stdin_open: true
    tty: true
networks:
  internal-network:
