# Generated by Django 4.0.10 on 2023-08-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0015_alter_profile_command_arguments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResallocMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.PositiveIntegerField(unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('task_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
