name: Integration Tests
on: [push]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages required to run job in a container
        run: |
          # sudo apt-get install -y podman
          pip3 install podman-compose
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run integration tests
        run: |
          # This is here to suppress a warning from GitHub
          # git config --global --add safe.directory /__w/openscanhub/openscanhub
          # TODO: This should be moved to `make lint` once we migrate to GitHub
          git clone https://github.com/release-engineering/kobo.git
          sed -i "s/RUN_TASKS_IN_FOREGROUND = 0/RUN_TASKS_IN_FOREGROUND = 1/g"  osh/worker/worker-local.conf
          containers/scripts/generate_integration_test_coverage.sh --force
          podman-compose down
